// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1) {
  return window['go']['main']['App']['CheckoutBranch'](arg1);
}

export function ChooseAndOpenRepo() {
  return window['go']['main']['App']['ChooseAndOpenRepo']();
}

export function CloneRepo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloneRepo'](arg1, arg2, arg3);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function CommitDiff(arg1) {
  return window['go']['main']['App']['CommitDiff'](arg1);
}

export function CommitFileDiff(arg1, arg2) {
  return window['go']['main']['App']['CommitFileDiff'](arg1, arg2);
}

export function CommitFiles(arg1) {
  return window['go']['main']['App']['CommitFiles'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function CreateBranchFrom(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBranchFrom'](arg1, arg2, arg3);
}

export function CreateRepo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRepo'](arg1, arg2, arg3);
}

export function DefaultBaseDir() {
  return window['go']['main']['App']['DefaultBaseDir']();
}

export function DeleteBranch(arg1, arg2) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2);
}

export function DeriveRepoName(arg1) {
  return window['go']['main']['App']['DeriveRepoName'](arg1);
}

export function DiscardFile(arg1) {
  return window['go']['main']['App']['DiscardFile'](arg1);
}

export function Fetch() {
  return window['go']['main']['App']['Fetch']();
}

export function FileContent(arg1) {
  return window['go']['main']['App']['FileContent'](arg1);
}

export function FileDiff(arg1, arg2) {
  return window['go']['main']['App']['FileDiff'](arg1, arg2);
}

export function FilePatchLines(arg1, arg2) {
  return window['go']['main']['App']['FilePatchLines'](arg1, arg2);
}

export function Identity() {
  return window['go']['main']['App']['Identity']();
}

export function IsGitRepo(arg1) {
  return window['go']['main']['App']['IsGitRepo'](arg1);
}

export function JoinPath(arg1, arg2) {
  return window['go']['main']['App']['JoinPath'](arg1, arg2);
}

export function OpenRepo(arg1) {
  return window['go']['main']['App']['OpenRepo'](arg1);
}

export function OperationChoices() {
  return window['go']['main']['App']['OperationChoices']();
}

export function Operations() {
  return window['go']['main']['App']['Operations']();
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PickRepo() {
  return window['go']['main']['App']['PickRepo']();
}

export function Publish(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['Publish'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function PublishDefaults() {
  return window['go']['main']['App']['PublishDefaults']();
}

export function Pull() {
  return window['go']['main']['App']['Pull']();
}

export function Push() {
  return window['go']['main']['App']['Push']();
}

export function PushSetUpstream(arg1) {
  return window['go']['main']['App']['PushSetUpstream'](arg1);
}

export function ReadConflictFile(arg1) {
  return window['go']['main']['App']['ReadConflictFile'](arg1);
}

export function RepoFiles() {
  return window['go']['main']['App']['RepoFiles']();
}

export function ResolveConflicts(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflicts'](arg1, arg2);
}

export function RunOperation(arg1, arg2) {
  return window['go']['main']['App']['RunOperation'](arg1, arg2);
}

export function RunRawGit(arg1) {
  return window['go']['main']['App']['RunRawGit'](arg1);
}

export function SetIdentity(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIdentity'](arg1, arg2, arg3);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['main']['App']['StageFile'](arg1);
}

export function StageLines(arg1, arg2, arg3) {
  return window['go']['main']['App']['StageLines'](arg1, arg2, arg3);
}

export function StashApply(arg1) {
  return window['go']['main']['App']['StashApply'](arg1);
}

export function StashDrop(arg1) {
  return window['go']['main']['App']['StashDrop'](arg1);
}

export function StashPop(arg1) {
  return window['go']['main']['App']['StashPop'](arg1);
}

export function StashSave(arg1, arg2) {
  return window['go']['main']['App']['StashSave'](arg1, arg2);
}

export function StashShow(arg1) {
  return window['go']['main']['App']['StashShow'](arg1);
}

export function Stashes() {
  return window['go']['main']['App']['Stashes']();
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['main']['App']['UnstageFile'](arg1);
}
