// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';

export function AbortOperation():Promise<engine.RepoSnapshot>;

export function AddRemote(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function AmendCommit(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function CheckoutBranch(arg1:string):Promise<engine.RepoSnapshot>;

export function CheckoutRemoteBranch(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function CherryPick(arg1:string):Promise<engine.RepoSnapshot>;

export function ChooseAndOpenRepo():Promise<engine.RepoSnapshot>;

export function CloneRepo(arg1:string,arg2:string,arg3:number):Promise<engine.RepoSnapshot>;

export function CloseWindow():Promise<void>;

export function Commit(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function CommitDiff(arg1:string):Promise<string>;

export function CommitFileDiff(arg1:string,arg2:string):Promise<string>;

export function CommitFiles(arg1:string):Promise<Array<engine.CommitFileDTO>>;

export function ContinueOperation():Promise<engine.RepoSnapshot>;

export function CreateBranch(arg1:string):Promise<engine.RepoSnapshot>;

export function CreateBranchFrom(arg1:string,arg2:string,arg3:boolean):Promise<engine.RepoSnapshot>;

export function CreateRepo(arg1:string,arg2:string,arg3:string):Promise<engine.RepoSnapshot>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<engine.RepoSnapshot>;

export function DefaultBaseDir():Promise<string>;

export function DeleteBranch(arg1:string,arg2:boolean):Promise<engine.RepoSnapshot>;

export function DeleteTag(arg1:string):Promise<engine.RepoSnapshot>;

export function DeriveRepoName(arg1:string):Promise<string>;

export function DiscardFile(arg1:string):Promise<engine.RepoSnapshot>;

export function DiscardedFiles():Promise<Array<engine.DiscardRecord>>;

export function Fetch():Promise<engine.RepoSnapshot>;

export function FileContent(arg1:string):Promise<engine.FileContentDTO>;

export function FileDiff(arg1:string,arg2:boolean):Promise<string>;

export function FilePatchLines(arg1:string,arg2:boolean):Promise<engine.FilePatch>;

export function Identity():Promise<string|string>;

export function InitRepoHere(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function InspectFolder(arg1:string):Promise<engine.FolderInfo>;

export function IsGitRepo(arg1:string):Promise<boolean>;

export function IsWindowMaximised():Promise<boolean>;

export function JoinPath(arg1:string,arg2:string):Promise<string>;

export function MergeBranch(arg1:string,arg2:boolean,arg3:boolean):Promise<engine.RepoSnapshot>;

export function MinimiseWindow():Promise<void>;

export function OpenRepo(arg1:string):Promise<engine.RepoSnapshot>;

export function OperationChoices():Promise<engine.OperationChoices>;

export function Operations():Promise<Array<engine.OperationSummary>>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickRepo():Promise<string>;

export function Publish(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:boolean):Promise<engine.PublishResult>;

export function PublishDefaults():Promise<engine.PublishDefaults>;

export function Pull():Promise<engine.RepoSnapshot>;

export function Push():Promise<engine.RepoSnapshot>;

export function PushAllTags(arg1:string):Promise<engine.RepoSnapshot>;

export function PushSetUpstream(arg1:string):Promise<engine.RepoSnapshot>;

export function PushTag(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function ReadConflictFile(arg1:string):Promise<engine.ConflictFile>;

export function RebaseOnto(arg1:string):Promise<engine.RepoSnapshot>;

export function RemoveRemote(arg1:string):Promise<engine.RepoSnapshot>;

export function RenameBranch(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function RepoFiles():Promise<Array<engine.RepoFileDTO>>;

export function ResetTo(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function ResolveConflicts(arg1:string,arg2:Array<engine.ConflictChoice>):Promise<engine.RepoSnapshot>;

export function RestoreDiscarded(arg1:string):Promise<engine.RepoSnapshot>;

export function RevertCommit(arg1:string):Promise<engine.RepoSnapshot>;

export function RunOperation(arg1:string,arg2:Record<string, string>):Promise<engine.RunResult>;

export function RunRawGit(arg1:string):Promise<engine.RunResult>;

export function SetIdentity(arg1:string,arg2:string,arg3:boolean):Promise<engine.RepoSnapshot>;

export function SetRemoteURL(arg1:string,arg2:string):Promise<engine.RepoSnapshot>;

export function Snapshot():Promise<engine.RepoSnapshot>;

export function StageAll():Promise<engine.RepoSnapshot>;

export function StageFile(arg1:string):Promise<engine.RepoSnapshot>;

export function StageLines(arg1:string,arg2:boolean,arg3:Array<number>):Promise<engine.RepoSnapshot>;

export function StashApply(arg1:number):Promise<engine.RepoSnapshot>;

export function StashDrop(arg1:number):Promise<engine.RepoSnapshot>;

export function StashPop(arg1:number):Promise<engine.RepoSnapshot>;

export function StashSave(arg1:string,arg2:boolean):Promise<engine.RepoSnapshot>;

export function StashShow(arg1:number):Promise<string>;

export function Stashes():Promise<Array<engine.StashEntryDTO>>;

export function ToggleMaximiseWindow():Promise<void>;

export function UndoLast():Promise<engine.RepoSnapshot>;

export function UnstageAll():Promise<engine.RepoSnapshot>;

export function UnstageFile(arg1:string):Promise<engine.RepoSnapshot>;
