// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckoutBranch(arg1) {
  return window['go']['main']['App']['CheckoutBranch'](arg1);
}

export function ChooseAndOpenRepo() {
  return window['go']['main']['App']['ChooseAndOpenRepo']();
}

export function CloneRepo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloneRepo'](arg1, arg2, arg3);
}

export function Commit(arg1, arg2) {
  return window['go']['main']['App']['Commit'](arg1, arg2);
}

export function CommitDiff(arg1) {
  return window['go']['main']['App']['CommitDiff'](arg1);
}

export function CommitFileDiff(arg1, arg2) {
  return window['go']['main']['App']['CommitFileDiff'](arg1, arg2);
}

export function CommitFiles(arg1) {
  return window['go']['main']['App']['CommitFiles'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['main']['App']['CreateBranch'](arg1);
}

export function CreateRepo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRepo'](arg1, arg2, arg3);
}

export function DefaultBaseDir() {
  return window['go']['main']['App']['DefaultBaseDir']();
}

export function DeriveRepoName(arg1) {
  return window['go']['main']['App']['DeriveRepoName'](arg1);
}

export function DiscardFile(arg1) {
  return window['go']['main']['App']['DiscardFile'](arg1);
}

export function Fetch() {
  return window['go']['main']['App']['Fetch']();
}

export function FileDiff(arg1, arg2) {
  return window['go']['main']['App']['FileDiff'](arg1, arg2);
}

export function Identity() {
  return window['go']['main']['App']['Identity']();
}

export function JoinPath(arg1, arg2) {
  return window['go']['main']['App']['JoinPath'](arg1, arg2);
}

export function OpenRepo(arg1) {
  return window['go']['main']['App']['OpenRepo'](arg1);
}

export function Operations() {
  return window['go']['main']['App']['Operations']();
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function PickRepo() {
  return window['go']['main']['App']['PickRepo']();
}

export function Publish(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Publish'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Pull() {
  return window['go']['main']['App']['Pull']();
}

export function Push() {
  return window['go']['main']['App']['Push']();
}

export function RunOperation(arg1, arg2) {
  return window['go']['main']['App']['RunOperation'](arg1, arg2);
}

export function RunRawGit(arg1) {
  return window['go']['main']['App']['RunRawGit'](arg1);
}

export function SetIdentity(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetIdentity'](arg1, arg2, arg3);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['main']['App']['StageFile'](arg1);
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['main']['App']['UnstageFile'](arg1);
}
